---
title: "TerrorMappingWriteup"
author: "Alex Rizzo-Banks"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: show
    number_sections: TRUE
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Read-In}
TerrorData = read.csv(file = "~/GW_ClassStuff/Data_Science_exploration/TerrorDB/TerrorData.csv",)
#"eventid" is structured according to date and then sequential ID of the incident (in case of multiple days), so: YYYYMMDD0001,0002,0003, etc
GTD1 = subset(TerrorData, TerrorData$eventid>200109210000)
#September 21st 2001 is the day after George Bush officially declared the U.S. War on Terror. We'll look at attacks since he said that.
library(dplyr)
GTDalex <- GTD1 %>% select(-c(approxdate,
                           region,
                           latitude, longitude,
                           specificity,
                           alternative,
                           attacktype1, attacktype2, attacktype3,         targtype1, targsubtype1, targtype2, targsubtype2, targtype3, targsubtype3,
                           natlty1, natlty2, natlty3, 
                           gname3, gsubname3, guncertain3, 
                           claimmode, 
                           claim2, claimmode2, claimmode2_txt, 
                           claim3, claimmode3, claimmode3_txt, 
                           weaptype1, weaptype2, weapsubtype1, weapsubtype2,
                  weaptype3, weaptype3_txt, weapsubtype3, weapsubtype3_txt,
                  weaptype4, weaptype4_txt, weapsubtype4, weapsubtype4_txt,
                  nkillus, nwoundus, 
                  propextent, 
          nhostkidus, nhours, ndays, divert, kidhijcountry, hostkidoutcome,
      ransom, ransomamt, ransomamtus, ransompaid, ransompaidus, ransomnote,
                            scite1, scite2, scite3, 
                            INT_ANY))
#We have removed 60 variables to narrow down the dataset for the scope of this class. Information on what was removed will be added later.
colnames(GTDalex) = c(
  "Chronological ID", "Year", "Month", "Day",
  "Attack ran multiple days?", "Date of resolution", 
  "Country code", "Country", "Region", "Province or state", "City", "Attack occurred within city limits?", "Description of location", 
  
  "Description of attack", "Attack meets Criteria 1?", "Attack meets Criteria 2?", "Attack meets Criteria 3?", "Terror label debated?", "Alternate label", "Multiple attacks?", 
  
  "Attack successful?", "Attackers commit suicide?", "Primary mode of attack", "Secondary mode of attack", "Tertiary mode of attack", 
  
  "Target primary type", 
  "Target secondary type", 
  "Targeted entity", 
  "Description of target", 
  "Nationality of target", 
  
  "2nd target primary type",
  "2nd target secondary type", 
  "2nd targeted entity", 
  "Description of 2nd target",
  "Nationality of 2nd target",
  
  "3rd target primary type",
  "3rd target secondary type", 
  "3rd targeted entity", 
  "Description of 3rd target",
  "Nationality of 3rd target",
  
  "Terror group name", "Terror group subname", "2nd terror group name", "2nd terror group subname", "Motive behind attack", "Terror group unconfirmed", "2nd terror group unconfirmed", 
  "Attack by single individual?", "Number of attackers", "Number of attackers captured",
  
  "Group claimed responsibility for attack?", "Mode of claim", "Competing claims?",
  
  "Primary weapon type", "Primary weapon subtype", "Secondary weapon type", "Secondary weapon subtype", "Description of weapon",
  
  "Total number of casualties", "Number of attackers killed", "Total number of wounded", "Number of attackers wounded", 
  "Damage. to property present?", "Level of property damage", "Total value of property damage", "Note on property damage",
  
  "Kidnapping occurred?", "Number kidnapped", "Outcome of kidnapping", "Number of hostages released",
  
  "Misc. notes", "Database used", 
  "Attacker nationality different from country?", "Attacker nationality different from target's?", "Target's nationality different from country?",
  
  "IDs of related attacks"
  )
library(ezids)
str(GTDalex)

write.csv(GTDalex, file = "C:/Users/arizz/OneDrive/Documents/GW_ClassStuff/Data_Science_exploration/TerrorIDS")
```